{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    {{- include "griot-and-grits.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      {{- include "griot-and-grits.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "griot-and-grits.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
      - name: minio
        image: {{ printf "%s:%s" .Values.minio.image.repository .Values.minio.image.tag }}
        args:
        - server
        - /data
        - --console-address
        - :9001
        ports:
        - containerPort: 9000
          name: api
          protocol: TCP
        - containerPort: 9001
          name: console
          protocol: TCP
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.minio.auth.rootUser | quote }}
        - name: MINIO_ROOT_PASSWORD
          value: {{ .Values.minio.auth.rootPassword | quote }}
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        {{- if .Values.minio.persistence.enabled }}
        persistentVolumeClaim:
          claimName: minio-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
